/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sd.socket.client.project;

import com.mycompany.paquete.Sala;
import com.mycompany.paquete.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class SalaForm extends FormularioObserver {
    private GameClient gameClient;
    private Sala room;
    private Integer token;
    private String nombre;
    
    public SalaForm(GameClient gameClient) {
        initComponents();
        this.gameClient = gameClient;
        this.gameClient.changeForm(this);
    }
    
    @Override
    public void setRoom(Sala room){
        this.room = room;
        
        jLabel1.setText("Token Sala: "+this.room.getToken());
        jLabel2.setText("Nombre Sala: "+this.room.getName());
        jLabel3.setText("Creador Sala: "+this.room.getCreador().getUsername());
    }
    
    @Override
    public void  hadARequestFrom(Usuario usuario){
        String nombre = usuario.getUsername();
        int resultado = JOptionPane.showOptionDialog(
                this,
                "¿Desea aceptar o rechazar la acción?",
                "El usuario "+ nombre+" quiere unirse a la sala",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // Icono predeterminado
                new Object[]{"Aceptar", "Rechazar"}, // Texto de los botones
                "Aceptar" // Botón predeterminado
        );
        switch (resultado) {
            case JOptionPane.YES_OPTION:
                System.out.println("Has seleccionado 'Aceptar'.");
                gameClient.handleAcceptRequestJoin(token, usuario);
                break;
            case JOptionPane.NO_OPTION:
                System.out.println("Has seleccionado 'Rechazar'.");
                gameClient.handleRejectRequestJoin(token, usuario);
                break;
            default:
                System.out.println("Cuadro de diálogo cerrado sin seleccionar una opción.");
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SALA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
